CREATE TABLE dim_country 
(
	Id INT auto_increment primary key,
    country_code	VARCHAR(512),
    country_name	VARCHAR(512),
    region	VARCHAR(512)
);

INSERT INTO dim_country (country_code, country_name, region) VALUES
	('USA', 'United States', 'North America'),
	('CHN', 'China', 'Asia'),
	('IND', 'India', 'Asia'),
	('BRA', 'Brazil', 'South America'),
	('IDN', 'Indonesia', 'Asia'),
	('PAK', 'Pakistan', 'Asia'),
	('NGA', 'Nigeria', 'Africa'),
	('BGD', 'Bangladesh', 'Asia'),
	('RUS', 'Russia', 'Europe'),
	('MEX', 'Mexico', 'North America'),
	('JPN', 'Japan', 'Asia'),
	('ETH', 'Ethiopia', 'Africa'),
	('PHL', 'Philippines', 'Asia'),
	('EGY', 'Egypt', 'Africa'),
	('VNM', 'Vietnam', 'Asia'),
	('COD', 'Democratic Republic of the Congo', 'Africa'),
	('TUR', 'Turkey', 'Europe'),
	('IRN', 'Iran', 'Asia'),
	('DEU', 'Germany', 'Europe'),
	('THA', 'Thailand', 'Asia'),
	('GBR', 'United Kingdom', 'Europe'),
	('FRA', 'France', 'Europe'),
	('ITA', 'Italy', 'Europe'),
	('TZA', 'Tanzania', 'Africa'),
	('ZAF', 'South Africa', 'Africa'),
	('KEN', 'Kenya', 'Africa'),
	('KOR', 'South Korea', 'Asia'),
	('COL', 'Colombia', 'South America'),
	('ESP', 'Spain', 'Europe'),
	('ARG', 'Argentina', 'South America'),
	('UGA', 'Uganda', 'Africa'),
	('UKR', 'Ukraine', 'Europe'),
	('DZA', 'Algeria', 'Africa'),
	('SDN', 'Sudan', 'Africa'),
	('IRQ', 'Iraq', 'Asia'),
	('AFG', 'Afghanistan', 'Asia'),
	('POL', 'Poland', 'Europe'),
	('CAN', 'Canada', 'North America'),
	('MAR', 'Morocco', 'Africa'),
	('SAU', 'Saudi Arabia', 'Asia'),
	('PER', 'Peru', 'South America'),
	('VEN', 'Venezuela', 'South America'),
	('MYS', 'Malaysia', 'Asia'),
	('UZB', 'Uzbekistan', 'Asia'),
	('MOZ', 'Mozambique', 'Africa'),
	('GHA', 'Ghana', 'Africa'),
	('YEM', 'Yemen', 'Asia'),
	('NPL', 'Nepal', 'Asia'),
	('AGO', 'Angola', 'Africa'),
	('AUS', 'Australia', 'Oceania'),
	('MDG', 'Madagascar', 'Africa'),
	('CMR', 'Cameroon', 'Africa'),
	('CIV', 'Ivory Coast', 'Africa'),
	('NLD', 'Netherlands', 'Europe'),
	('CHL', 'Chile', 'South America'),
	('KAZ', 'Kazakhstan', 'Asia'),
	('ECU', 'Ecuador', 'South America'),
	('SEN', 'Senegal', 'Africa'),
	('MLI', 'Mali', 'Africa'),
	('ROU', 'Romania', 'Europe'),
	('BEL', 'Belgium', 'Europe'),
	('GRC', 'Greece', 'Europe'),
	('CZE', 'Czech Republic', 'Europe'),
	('BTN', 'Bhutan', 'Asia'),
	('CHE', 'Switzerland', 'Europe'),
	('BDI', 'Burundi', 'Africa'),
	('BOL', 'Bolivia', 'South America'),
	('PRT', 'Portugal', 'Europe'),
	('SVK', 'Slovakia', 'Europe'),
	('TUN', 'Tunisia', 'Africa'),
	('ISR', 'Israel', 'Asia'),
	('HUN', 'Hungary', 'Europe'),
	('SWE', 'Sweden', 'Europe'),
	('BLR', 'Belarus', 'Europe'),
	('ARE', 'United Arab Emirates', 'Asia'),
	('HND', 'Honduras', 'North America'),
	('TJK', 'Tajikistan', 'Asia'),
	('AUT', 'Austria', 'Europe'),
	('SRB', 'Serbia', 'Europe'),
	('SUI', 'Suriname', 'South America'),
	('PRI', 'Puerto Rico', 'North America'),
	('BGR', 'Bulgaria', 'Europe'),
	('LBY', 'Libya', 'Africa'),
	('LBN', 'Lebanon', 'Asia'),
	('URY', 'Uruguay', 'South America'),
	('URY', 'Sri Lanka', 'Asia'),
	('PRK', 'North Korea', 'Asia'),
	('KGZ', 'Kyrgyzstan', 'Asia'),
	('DJI', 'Djibouti', 'Africa'),
	('GUI', 'Guinea', 'Africa'),
	('LVA', 'Latvia', 'Europe'),
	('KEN', 'Kuwait', 'Asia'),
	('SVN', 'Slovenia', 'Europe'),
	('GTM', 'Guatemala', 'North America');